export const translations = {
  en: {
    portal_title: "ILMA Student Portal",
    command_center: "Command Center",
    welcome_msg: "Welcome to the next generation of academic management. Securely monitor your course trajectory.",
    dashboard: "Dashboard",
    grades: "Academic Nexus",
    financial: "Financial Ledger",
    assignments: "Assignment Hub",
    campus: "Campus Pulse",
    appearance: "Appearance",
    portal: "Portal Node",
    profile: "Student Profile",
    schedule: "Class Schedule",
    notifications: "Notifications",
    logout: "Log Out",
    search: "Search content...",
    academic_trajectory: "Academic Trajectory",
    system_alerts: "System Alerts",
    attendance: "Attendance Pulse",
    gpa: "GPA Estimate",
    fee_breakdown: "Fee Breakdown",
    scholarship: "Scholarship Node",
    extracurricular: "Society Events",
    assignment_header: "Assignment Sanctuary",
    assignment_subtitle: "Securely monitor academic objectives and track feedback nodes.",
    active_deadlines: "Active Deadlines",
    performance_equilibrium: "Performance Equilibrium",
    mission_history: "Mission History Matrix",
    initialize_uplink: "Initialize Uplink",
    language_label: "Eng",
    // Grades Page
    grades_title: "Academic Nexus",
    grades_subtitle: "Quantum visualization of your academic trajectory and degree synchronization.",
    active_semester: "Active Semester Node",
    semester_batch: "Spring 2026 Batch",
    module_entry: "Module Entry",
    index: "Index",
    rank: "Rank",
    sync_status: "Sync Status",
    degree_completion: "Degree Completion Hub",
    earned_credits: "Earned Credits",
    academic_status: "Academic Status",
    cumulative_index: "Cumulative Index",
    secure_transcript: "Secure Transcript Extraction",
    // Schedule Page
    schedule_title: "Class Timetable",
    schedule_subtitle: "Manage your weekly schedule and academic commitments.",
    weekly_schedule: "Weekly Schedule",
    spring_semester: "Spring Semester 2026",
    time_slot: "Time Slot",
    export_pdf: "Export PDF",
    // Notifications Page
    bulletin_center: "Bulletin Center",
    bulletin_subtitle: "Manage your academic alerts and university-wide announcements.",
    dismiss_all: "Dismiss All",
    unread_alerts: "Unread Alerts"
  },
  ur: {
    portal_title: "علما اسٹوڈنٹ پورٹل",
    command_center: "کمانڈ سینٹر",
    welcome_msg: "تعلیمی انتظام کی اگلی نسل میں خوش آمدید۔ اپنے کورس کی نگرانی باحفاظت کریں۔",
    dashboard: "ڈیش بورڈ",
    grades: "تعلیمی رابطہ",
    financial: "مالیاتی رجسٹر",
    assignments: "اسائنمنٹ سینٹر",
    campus: "کیمپس اپ ڈیٹس",
    appearance: "ظاہری ترتیبات",
    portal: "پورٹل نوڈ",
    profile: "طالب علم کی پروفائل",
    schedule: "کلاس شیڈول",
    notifications: "سسٹم اطلاعات",
    logout: "لاگ آؤٹ",
    search: "تلاش کریں...",
    academic_trajectory: "تعلیمی گراف",
    system_alerts: "سسٹم الرٹس",
    attendance: "حاضری کی شرح",
    gpa: "جی پی اے ٹریکر",
    fee_breakdown: "فیس کی تفصیل",
    scholarship: "اسکالرشپ نوڈ",
    extracurricular: "کیمپس ایونٹس",
    assignment_header: "اسائنمنٹ سینکچری",
    assignment_subtitle: "اپنے تعلیمی اہداف کی نگرانی کریں اور فیڈ بیک ٹریک کریں۔",
    active_deadlines: "فعال ڈیڈ لائنز",
    performance_equilibrium: "کارکردگی کا توازن",
    mission_history: "مشن ہسٹری میٹرکس",
    initialize_uplink: "اپ لنک شروع کریں",
    language_label: "اردو",
    // Grades Page
    grades_title: "تعلیمی رابطہ",
    grades_subtitle: "آپ کے تعلیمی سفر اور ڈگری کی تکمیل کا کوانٹم تصور۔",
    active_semester: "فعال سمسٹر نوڈ",
    semester_batch: "بہار 2026 بیچ",
    module_entry: "ماڈیول انٹری",
    index: "انڈیکس",
    rank: "رینک",
    sync_status: "مطابقت کی صورتحال",
    degree_completion: "ڈگری کی تکمیل کا مرکز",
    earned_credits: "حاصل کردہ کریڈٹ",
    academic_status: "تعلیمی حیثیت",
    cumulative_index: "مجموعی انڈیکس",
    secure_transcript: "محفوظ ٹرانسکرپٹ کا حصول",
    // Schedule Page
    schedule_title: "کلاس ٹائم ٹیبل",
    schedule_subtitle: "اپنے ہفتہ وار شیڈول اور تعلیمی مصروفیات کا انتظام کریں۔",
    weekly_schedule: "ہفتہ وار شیڈول",
    spring_semester: "بہار سمسٹر 2026",
    time_slot: "وقت کا وقفہ",
    export_pdf: "پی ڈی ایف ایکسپورٹ",
    // Notifications Page
    bulletin_center: "بلیٹن سینٹر",
    bulletin_subtitle: "اپنے تعلیمی انتباہات اور یونیورسٹی کے اعلانات کا انتظام کریں۔",
    dismiss_all: "تمام ختم کریں",
    unread_alerts: "غیر پڑھے ہوئے الرٹس"
  },
  ur_roman: {
    portal_title: "ILMA Student Portal",
    command_center: "Command Center",
    welcome_msg: "Academic management ki agli nasal mein khush amdeed. Apne courses ki nigraani karein.",
    dashboard: "Dashboard",
    grades: "Parhai Ka Link",
    financial: "Fees Ka Hisab",
    assignments: "Assignment Hub",
    campus: "Campus Ki Khabrein",
    appearance: "Design Badalain",
    portal: "Portal Node",
    profile: "Student Profile",
    schedule: "Class Ka Time",
    notifications: "Alerts & Messages",
    logout: "Bahir Nikalain",
    search: "Kuch dhondein...",
    academic_trajectory: "Parhai Ka Graph",
    system_alerts: "Zaroori Khabrein",
    attendance: "Hazri Ka Pulse",
    gpa: "GPA Ka Hisab",
    fee_breakdown: "Fees Ki Detail",
    scholarship: "Scholarship Node",
    extracurricular: "Baher Ki Activities",
    assignment_header: "Assignment Sanctuary",
    assignment_subtitle: "Apne parhai ke targets check karein aur feedback dekhain.",
    active_deadlines: "Active Deadlines",
    performance_equilibrium: "Performance Check",
    mission_history: "Purani History",
    initialize_uplink: "Upload Karein",
    language_label: "Roman",
    // Grades Page
    grades_title: "Parhai Ka Link",
    grades_subtitle: "Aapki academic history aur degree syncing ki digital tasveer.",
    active_semester: "Active Semester Node",
    semester_batch: "Spring 2026 Batch",
    module_entry: "Course Name",
    index: "GPA",
    rank: "Grade",
    sync_status: "Result Status",
    degree_completion: "Degree Poori Hone Ka Hub",
    earned_credits: "Poore Kiye Gaye Credits",
    academic_status: "Pahrhai Ki Status",
    cumulative_index: "Total GPA",
    secure_transcript: "Transcript Download Karein",
    // Schedule Page
    schedule_title: "Class Ka Time Table",
    schedule_subtitle: "Apna hafta-war schedule check karein.",
    weekly_schedule: "Hafta-war Schedule",
    spring_semester: "Spring Semester 2026",
    time_slot: "Time Slot",
    export_pdf: "PDF Download",
    // Notifications Page
    bulletin_center: "Alerts Center",
    bulletin_subtitle: "Apne campus notifications aur news check karein.",
    dismiss_all: "Sab Hatayein",
    unread_alerts: "Naye Alerts"
  }
};

export const applyLanguage = (lang) => {
  localStorage.setItem("portal-lang", lang);
  document.documentElement.lang = lang === 'ur' ? 'ur' : 'en';
  document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
};

export const getTranslation = (key) => {
  const lang = localStorage.getItem("portal-lang") || "en";
  return translations[lang][key] || translations['en'][key] || key;
};

