export const translations = {
  en: {
    portal_title: "ILMA Student Portal",
    command_center: "Command Center",
    welcome_msg:
      "Welcome to the next generation of academic management. Securely monitor your course trajectory.",
    dashboard: "Dashboard",
    grades: "Academic Nexus",
    financial: "Financial Ledger",
    assignments: "Assignment Hub",
    campus: "Campus Pulse",
    appearance: "Appearance",
    portal: "Portal Node",
    profile: "Student Profile",
    schedule: "Class Schedule",
    notifications: "Notifications",
    logout: "Log Out",
    search: "Search content...",
    academic_trajectory: "Academic Trajectory",
    system_alerts: "System Alerts",
    attendance: "Attendance Pulse",
    gpa: "GPA Estimate",
    fee_breakdown: "Fee Breakdown",
    scholarship: "Scholarship Node",
    extracurricular: "Society Events",
    assignment_header: "Assignment Sanctuary",
    assignment_subtitle:
      "Securely monitor academic objectives and track feedback nodes.",
    active_deadlines: "Active Deadlines",
    performance_equilibrium: "Performance Equilibrium",
    mission_history: "Mission History Matrix",
    initialize_uplink: "Initialize Uplink",
    language_label: "Eng",
    // Grades Page
    grades_title: "Academic Nexus",
    grades_subtitle:
      "Quantum visualization of your academic trajectory and degree synchronization.",
    active_semester: "Active Semester Node",
    semester_batch: "Spring 2026 Batch",
    module_entry: "Module Entry",
    index: "Index",
    rank: "Rank",
    sync_status: "Sync Status",
    degree_completion: "Degree Completion Hub",
    earned_credits: "Earned Credits",
    academic_status: "Academic Status",
    cumulative_index: "Cumulative Index",
    secure_transcript: "Secure Transcript Extraction",
    // Schedule Page
    schedule_title: "Class Timetable",
    schedule_subtitle: "Manage your weekly schedule and academic commitments.",
    weekly_schedule: "Weekly Schedule",
    spring_semester: "Spring Semester 2026",
    time_slot: "Time Slot",
    export_pdf: "Export PDF",
    // Notifications Page
    bulletin_center: "Bulletin Center",
    bulletin_subtitle:
      "Manage your academic alerts and university-wide announcements.",
    dismiss_all: "Dismiss All",
    unread_alerts: "Unread Alerts",
    // Common / reused across pages
    common_status: "Status",
    common_progress: "Progress",
    common_join: "Join",
    common_view: "View",
    common_cancel: "Cancel",
    day_mon: "Mon",
    day_tue: "Tue",
    day_wed: "Wed",
    day_thu: "Thu",
    day_fri: "Fri",
    day_sat: "Sat",
    day_sun: "Sun",
    // Auth pages (Login / Signup / Forgot / Reset)
    auth_login_heading: "Welcome back",
    auth_login_subtitle: "Sign in to your student account to continue.",
    auth_email_label: "Email Address",
    auth_password_label: "Password",
    auth_forgot_password: "Forgot Password?",
    auth_signing_in: "Signing in…",
    auth_sign_in: "Sign In",
    auth_no_account: "Don't have an account?",
    auth_create_account: "Create Account",
    auth_uni_name: "ILMA University",
    auth_student_portal: "Student Portal",
    auth_panel_login_desc:
      "Access your courses, grades, schedules and campus notifications — all in one place.",
    auth_stat_students: "15,000+ Active Students",
    auth_stat_faculty: "200+ Expert Faculty",
    auth_stat_ranked: "Ranked #1 Private University",
    auth_join_ilma: "Join ILMA",
    auth_signup_panel_title2: "Hackathon 2026",
    auth_panel_signup_desc:
      "Create your student account and get instant access to all university resources, events, and more.",
    auth_feature_instant: "Instant Access on Sign Up",
    auth_feature_secure: "Secure & Encrypted Data",
    auth_feature_247: "24 / 7 Portal Availability",
    auth_feature_leaderboard: "Hackathon Leaderboard",
    auth_signup_subtitle: "Register with your student details below.",
    auth_fullname_label: "Full Name",
    auth_studentid_label: "Student ID",
    auth_creating_account: "Creating Account…",
    auth_have_account: "Already have an account?",
    auth_sign_in_link: "Sign In",
    auth_forgot_heading: "Forgot Password?",
    auth_forgot_subtitle:
      "Enter your registered email and we'll send you a password reset link.",
    auth_sending: "Sending…",
    auth_send_reset_link: "Send Reset Link",
    auth_back_to_login: "Back to Login",
    auth_reset_heading: "Set New Password",
    auth_reset_subtitle_prefix: "Create a strong password for",
    auth_new_password_label: "New Password",
    auth_confirm_password_label: "Confirm Password",
    auth_updating: "Updating…",
    auth_reset_password_btn: "Reset Password",
    auth_passwords_match: "✓ Passwords match",
    auth_passwords_no_match: "✗ Passwords do not match",
    auth_pw_weak: "Weak",
    auth_pw_fair: "Fair",
    auth_pw_good: "Good",
    auth_pw_strong: "Strong",
    auth_pw_suffix: "password",
    auth_email_placeholder: "yourname@ilmauniversity.edu",
    auth_password_placeholder: "Enter your password",
    auth_password_placeholder_create: "Create a strong password",
    auth_fullname_placeholder: "John Doe",
    auth_studentid_placeholder: "2023-CS-001",
    auth_new_password_placeholder: "At least 6 characters",
    auth_confirm_password_placeholder: "Repeat your new password",
    // Profile Page
    profile_title: "Student Identity",
    profile_subtitle: "Manage your academic profile and digital credentials.",
    profile_official_id: "Official ID / 2026",
    profile_valid_thru: "Valid Thru",
    profile_scan_verify: "Scan to Verify",
    profile_qr_note:
      "Property of ILMA University. If found, return to administration.",
    profile_active: "Active",
    profile_stat_gpa: "Aggregate GPA",
    profile_stat_attendance: "Attendance",
    profile_stat_credits: "Total Credits",
    profile_stat_points: "Portal Points",
    profile_account_heading: "Account Profile",
    profile_account_subtitle: "Update your public identity on the portal.",
    profile_edit: "Edit Profile",
    profile_save: "Save Changes",
    profile_fullname_label: "Full Identity Name",
    profile_studentid_label: "Official Student ID",
    profile_email_label: "Verified Email Address",
    profile_bio_label: "Personal Academic Bio",
    profile_security_status: "Security Status",
    profile_reset_credentials: "Reset Credentials",
    profile_termination: "Termination",
    profile_deactivate: "Deactivate Session",
    // 404 / Error boundary
    notfound_error: "Error 404",
    notfound_title: "Page Not Found",
    notfound_desc:
      "The page you are looking for does not exist or may have been moved.",
    notfound_home: "Back to Home",
    notfound_portal: "Open Portal",
    error_title: "Something went wrong",
    error_desc: "The page failed to render. Please refresh or navigate again.",
    // Financial Page
    financial_subtitle:
      "Manage your fiscal node, track transactions, and monitor scholarship allocations.",
    financial_balance_hub: "Current Balance Hub",
    financial_scholarship_metrics: "Scholarship Metrics",
    financial_eligibility_sync: "Eligibility Sync",
    financial_ledger_matrix: "Ledger Matrix",
    financial_filter_hub: "Filter Hub",
    financial_apply_installments: "Apply Installments",
    financial_th_txid: "Transaction ID",
    financial_th_desc: "Description",
    financial_th_amount: "Amount",
    financial_th_method: "Method",
    generate_voucher: "Generate Voucher",
    // Campus Pulse Page
    campus_subtitle:
      "The digital heartbeat of ILMA. Synchronize with latest news, events, and campus guilds.",
    campus_live_stream: "Live Stream",
    campus_online: "Online",
    campus_historical_logs: "Historical Logs",
    campus_event_nexus: "Event Nexus Nodes",
    campus_guild_directory: "Verified Campus Guilds",
    campus_secure_token: "Secure Token",
    campus_join_node: "Join Node",
    campus_members_suffix: "Members",
    campus_digital_hub: "Digital Campus Hub",
    // Portal Page
    portal_active_enrollment: "Active Enrollment",
    portal_courses_suffix: "Courses",
    portal_no_courses: "No courses enrolled yet",
    portal_marketplace: "Marketplace",
    portal_timeline: "Timeline",
    // Appearance Page
    appearance_subtitle:
      "Reprogram your portal's appearance node and personalize your Command Center DNA.",
    appearance_theme_archetypes: "Theme Archetypes",
    appearance_mode_sync: "Mode Synchronizer",
    appearance_solar: "Solar",
    appearance_night: "Night",
    appearance_font_matrix: "Font Matrix",
    appearance_typography_scaling: "Typography Scaling",
    appearance_compact: "Compact",
    appearance_standard: "Standard",
    appearance_expanded: "Expanded",
    appearance_reset_protocols: "Reset All Protocols",
    appearance_factory_reboot: "Initialize Factory Reboot",
    // Assignments Page
    assignments_request_extension: "Request Extension",
    assignments_th_deployed: "Deployed Hub",
    assignments_th_index: "Index Score",
    assignments_th_remarks: "Faculty Remarks",
    assignments_score: "Score",
    // Schedule Page
    schedule_lunch_break: "Lunch Break",
    schedule_main_block: "Main Block",
    schedule_info_rooms: "Rooms 201-205, Labs",
    schedule_info_faculty_hours_title: "Faculty Hours",
    schedule_info_faculty_hours_text: "Mon-Thu: 10AM-12PM",
    schedule_info_note_title: "Note",
    schedule_info_note_text: "Lab sessions are mandatory.",
    // Home Page
    home_portal_btn: "Portal",
    home_sync_timetable: "Sync Timetable",
    home_student_node: "Student Node",
    home_uplink_active: "Uplink: Active",
    home_latency_prefix: "Latency",
    home_live_time: "Live Subsystem Time",
    home_active_sync: "Active Sync",
    home_temporal_alignment: "Temporal Alignment",
    home_weekly_engagement: "Weekly study engagement",
    home_status_optimized: "Status: Optimized",
    home_gpa_estimate: "GPA Estimate",
    home_academic_standing: "Academic Standing",
    home_superior_performance: "Superior performance detected.",
    home_presence_analytics: "Presence Analytics",
    home_maintain_trajectory: "Maintain trajectory.",
    home_bulletin_history: "Bulletin History",
    home_last_synced: "Last Synced",
    home_portal_version: "Portal Version 4.0.2 Stable",
    // Header
    header_no_match: "No pages match",
    header_search_placeholder: "Search pages...",
  },
  ur: {
    portal_title: "علما اسٹوڈنٹ پورٹل",
    command_center: "کمانڈ سینٹر",
    welcome_msg:
      "تعلیمی انتظام کی اگلی نسل میں خوش آمدید۔ اپنے کورس کی نگرانی باحفاظت کریں۔",
    dashboard: "ڈیش بورڈ",
    grades: "تعلیمی رابطہ",
    financial: "مالیاتی رجسٹر",
    assignments: "اسائنمنٹ سینٹر",
    campus: "کیمپس اپ ڈیٹس",
    appearance: "ظاہری ترتیبات",
    portal: "پورٹل نوڈ",
    profile: "طالب علم کی پروفائل",
    schedule: "کلاس شیڈول",
    notifications: "سسٹم اطلاعات",
    logout: "لاگ آؤٹ",
    search: "تلاش کریں...",
    academic_trajectory: "تعلیمی گراف",
    system_alerts: "سسٹم الرٹس",
    attendance: "حاضری کی شرح",
    gpa: "جی پی اے ٹریکر",
    fee_breakdown: "فیس کی تفصیل",
    scholarship: "اسکالرشپ نوڈ",
    extracurricular: "کیمپس ایونٹس",
    assignment_header: "اسائنمنٹ سینکچری",
    assignment_subtitle:
      "اپنے تعلیمی اہداف کی نگرانی کریں اور فیڈ بیک ٹریک کریں۔",
    active_deadlines: "فعال ڈیڈ لائنز",
    performance_equilibrium: "کارکردگی کا توازن",
    mission_history: "مشن ہسٹری میٹرکس",
    initialize_uplink: "اپ لنک شروع کریں",
    language_label: "اردو",
    // Grades Page
    grades_title: "تعلیمی رابطہ",
    grades_subtitle: "آپ کے تعلیمی سفر اور ڈگری کی تکمیل کا کوانٹم تصور۔",
    active_semester: "فعال سمسٹر نوڈ",
    semester_batch: "بہار 2026 بیچ",
    module_entry: "ماڈیول انٹری",
    index: "انڈیکس",
    rank: "رینک",
    sync_status: "مطابقت کی صورتحال",
    degree_completion: "ڈگری کی تکمیل کا مرکز",
    earned_credits: "حاصل کردہ کریڈٹ",
    academic_status: "تعلیمی حیثیت",
    cumulative_index: "مجموعی انڈیکس",
    secure_transcript: "محفوظ ٹرانسکرپٹ کا حصول",
    // Schedule Page
    schedule_title: "کلاس ٹائم ٹیبل",
    schedule_subtitle:
      "اپنے ہفتہ وار شیڈول اور تعلیمی مصروفیات کا انتظام کریں۔",
    weekly_schedule: "ہفتہ وار شیڈول",
    spring_semester: "بہار سمسٹر 2026",
    time_slot: "وقت کا وقفہ",
    export_pdf: "پی ڈی ایف ایکسپورٹ",
    // Notifications Page
    bulletin_center: "بلیٹن سینٹر",
    bulletin_subtitle:
      "اپنے تعلیمی انتباہات اور یونیورسٹی کے اعلانات کا انتظام کریں۔",
    dismiss_all: "تمام ختم کریں",
    unread_alerts: "غیر پڑھے ہوئے الرٹس",
    common_status: "حیثیت",
    common_progress: "پیش رفت",
    common_join: "شامل ہوں",
    common_view: "دیکھیں",
    common_cancel: "منسوخ کریں",
    day_mon: "پیر",
    day_tue: "منگل",
    day_wed: "بدھ",
    day_thu: "جمعرات",
    day_fri: "جمعہ",
    day_sat: "ہفتہ",
    day_sun: "اتوار",
    auth_login_heading: "خوش آمدید",
    auth_login_subtitle: "جاری رکھنے کے لیے اپنے اسٹوڈنٹ اکاؤنٹ میں لاگ اِن کریں۔",
    auth_email_label: "ای میل ایڈریس",
    auth_password_label: "پاس ورڈ",
    auth_forgot_password: "پاس ورڈ بھول گئے؟",
    auth_signing_in: "لاگ اِن ہو رہا ہے…",
    auth_sign_in: "لاگ اِن کریں",
    auth_no_account: "اکاؤنٹ نہیں ہے؟",
    auth_create_account: "اکاؤنٹ بنائیں",
    auth_uni_name: "علما یونیورسٹی",
    auth_student_portal: "اسٹوڈنٹ پورٹل",
    auth_panel_login_desc:
      "اپنے کورسز، گریڈز، شیڈول اور کیمپس اطلاعات تک ایک ہی جگہ رسائی حاصل کریں۔",
    auth_stat_students: "15,000+ فعال طلبہ",
    auth_stat_faculty: "200+ ماہر اساتذہ",
    auth_stat_ranked: "نمبر 1 پرائیویٹ یونیورسٹی",
    auth_join_ilma: "علما میں شامل ہوں",
    auth_signup_panel_title2: "ہیکاتھون 2026",
    auth_panel_signup_desc:
      "اپنا اسٹوڈنٹ اکاؤنٹ بنائیں اور یونیورسٹی کے تمام وسائل، ایونٹس اور مزید تک فوری رسائی حاصل کریں۔",
    auth_feature_instant: "سائن اپ پر فوری رسائی",
    auth_feature_secure: "محفوظ اور خفیہ کردہ ڈیٹا",
    auth_feature_247: "24 / 7 پورٹل دستیابی",
    auth_feature_leaderboard: "ہیکاتھون لیڈر بورڈ",
    auth_signup_subtitle: "نیچے اپنی طالب علمی تفصیلات کے ساتھ رجسٹر کریں۔",
    auth_fullname_label: "پورا نام",
    auth_studentid_label: "اسٹوڈنٹ آئی ڈی",
    auth_creating_account: "اکاؤنٹ بن رہا ہے…",
    auth_have_account: "پہلے سے اکاؤنٹ ہے؟",
    auth_sign_in_link: "لاگ اِن کریں",
    auth_forgot_heading: "پاس ورڈ بھول گئے؟",
    auth_forgot_subtitle:
      "اپنا رجسٹرڈ ای میل درج کریں، ہم آپ کو پاس ورڈ ری سیٹ لنک بھیجیں گے۔",
    auth_sending: "بھیجا جا رہا ہے…",
    auth_send_reset_link: "ری سیٹ لنک بھیجیں",
    auth_back_to_login: "لاگ اِن پر واپس جائیں",
    auth_reset_heading: "نیا پاس ورڈ سیٹ کریں",
    auth_reset_subtitle_prefix: "اس کے لیے مضبوط پاس ورڈ بنائیں",
    auth_new_password_label: "نیا پاس ورڈ",
    auth_confirm_password_label: "پاس ورڈ کی تصدیق کریں",
    auth_updating: "اپڈیٹ ہو رہا ہے…",
    auth_reset_password_btn: "پاس ورڈ ری سیٹ کریں",
    auth_passwords_match: "✓ پاس ورڈز مماثل ہیں",
    auth_passwords_no_match: "✗ پاس ورڈز مماثل نہیں ہیں",
    auth_pw_weak: "کمزور",
    auth_pw_fair: "درمیانہ",
    auth_pw_good: "اچھا",
    auth_pw_strong: "مضبوط",
    auth_pw_suffix: "پاس ورڈ",
    auth_email_placeholder: "yourname@ilmauniversity.edu",
    auth_password_placeholder: "اپنا پاس ورڈ درج کریں",
    auth_password_placeholder_create: "ایک مضبوط پاس ورڈ بنائیں",
    auth_fullname_placeholder: "جان ڈو",
    auth_studentid_placeholder: "2023-CS-001",
    auth_new_password_placeholder: "کم از کم 6 حروف",
    auth_confirm_password_placeholder: "اپنا نیا پاس ورڈ دوبارہ لکھیں",
    profile_title: "طالب علم کی شناخت",
    profile_subtitle: "اپنی تعلیمی پروفائل اور ڈیجیٹل اسناد کا انتظام کریں۔",
    profile_official_id: "سرکاری آئی ڈی / 2026",
    profile_valid_thru: "میعاد ختم",
    profile_scan_verify: "تصدیق کے لیے اسکین کریں",
    profile_qr_note: "یہ علما یونیورسٹی کی ملکیت ہے۔ ملنے پر انتظامیہ کو واپس کریں۔",
    profile_active: "فعال",
    profile_stat_gpa: "مجموعی جی پی اے",
    profile_stat_attendance: "حاضری",
    profile_stat_credits: "کل کریڈٹس",
    profile_stat_points: "پورٹل پوائنٹس",
    profile_account_heading: "اکاؤنٹ پروفائل",
    profile_account_subtitle: "پورٹل پر اپنی عوامی شناخت اپڈیٹ کریں۔",
    profile_edit: "پروفائل میں ترمیم کریں",
    profile_save: "تبدیلیاں محفوظ کریں",
    profile_fullname_label: "مکمل شناختی نام",
    profile_studentid_label: "سرکاری اسٹوڈنٹ آئی ڈی",
    profile_email_label: "تصدیق شدہ ای میل ایڈریس",
    profile_bio_label: "ذاتی تعلیمی تعارف",
    profile_security_status: "سیکیورٹی کی حیثیت",
    profile_reset_credentials: "اسناد ری سیٹ کریں",
    profile_termination: "اختتام",
    profile_deactivate: "سیشن غیر فعال کریں",
    notfound_error: "خرابی 404",
    notfound_title: "صفحہ نہیں ملا",
    notfound_desc: "آپ جس صفحے کی تلاش میں ہیں وہ موجود نہیں یا منتقل ہو چکا ہے۔",
    notfound_home: "ہوم پیج پر واپس جائیں",
    notfound_portal: "پورٹل کھولیں",
    error_title: "کچھ غلط ہو گیا",
    error_desc:
      "صفحہ لوڈ نہیں ہو سکا۔ براہ کرم دوبارہ کوشش کریں یا کسی اور صفحے پر جائیں۔",
    financial_subtitle:
      "اپنے مالیاتی نوڈ کا انتظام کریں، لین دین ٹریک کریں اور اسکالرشپ کی تقسیم کی نگرانی کریں۔",
    financial_balance_hub: "موجودہ بیلنس ہب",
    financial_scholarship_metrics: "اسکالرشپ کے اعداد و شمار",
    financial_eligibility_sync: "اہلیت مطابقت",
    financial_ledger_matrix: "لیجر میٹرکس",
    financial_filter_hub: "فلٹر ہب",
    financial_apply_installments: "قسطوں کے لیے درخواست دیں",
    financial_th_txid: "ٹرانزیکشن آئی ڈی",
    financial_th_desc: "تفصیل",
    financial_th_amount: "رقم",
    financial_th_method: "طریقہ",
    generate_voucher: "واؤچر بنائیں",
    campus_subtitle:
      "علما کی ڈیجیٹل دھڑکن۔ تازہ ترین خبروں، ایونٹس اور کیمپس تنظیموں سے جڑے رہیں۔",
    campus_live_stream: "لائیو اسٹریم",
    campus_online: "آن لائن",
    campus_historical_logs: "پرانی سرگرمیاں",
    campus_event_nexus: "ایونٹ نوڈز",
    campus_guild_directory: "تصدیق شدہ کیمپس تنظیمیں",
    campus_secure_token: "سیٹ محفوظ کریں",
    campus_join_node: "شامل ہوں",
    campus_members_suffix: "ممبرز",
    campus_digital_hub: "ڈیجیٹل کیمپس ہب",
    portal_active_enrollment: "فعال داخلہ",
    portal_courses_suffix: "کورسز",
    portal_no_courses: "ابھی کوئی کورس داخل نہیں کیا گیا",
    portal_marketplace: "مارکیٹ پلیس",
    portal_timeline: "ٹائم لائن",
    appearance_subtitle:
      "اپنے پورٹل کی ظاہری شکل کو دوبارہ ترتیب دیں اور کمانڈ سینٹر کو ذاتی بنائیں۔",
    appearance_theme_archetypes: "تھیم کی اقسام",
    appearance_mode_sync: "موڈ سنکرونائزر",
    appearance_solar: "دن کا موڈ",
    appearance_night: "رات کا موڈ",
    appearance_font_matrix: "فونٹ میٹرکس",
    appearance_typography_scaling: "فونٹ سائز",
    appearance_compact: "مختصر",
    appearance_standard: "معیاری",
    appearance_expanded: "بڑا",
    appearance_reset_protocols: "تمام ترتیبات ری سیٹ کریں",
    appearance_factory_reboot: "فیکٹری ری سیٹ شروع کریں",
    assignments_request_extension: "توسیع کی درخواست دیں",
    assignments_th_deployed: "جمع کرایا گیا کام",
    assignments_th_index: "انڈیکس اسکور",
    assignments_th_remarks: "فیکلٹی کی رائے",
    assignments_score: "اسکور",
    schedule_lunch_break: "کھانے کا وقفہ",
    schedule_main_block: "مین بلاک",
    schedule_info_rooms: "کمرے 201-205، لیبز",
    schedule_info_faculty_hours_title: "فیکلٹی اوقات",
    schedule_info_faculty_hours_text: "پیر تا جمعرات: صبح 10 تا دوپہر 12",
    schedule_info_note_title: "نوٹ",
    schedule_info_note_text: "لیب سیشنز میں حاضری لازمی ہے۔",
    home_portal_btn: "پورٹل",
    home_sync_timetable: "ٹائم ٹیبل دیکھیں",
    home_student_node: "اسٹوڈنٹ نوڈ",
    home_uplink_active: "اپ لنک: فعال",
    home_latency_prefix: "لیٹنسی",
    home_live_time: "لائیو سسٹم وقت",
    home_active_sync: "فعال مطابقت",
    home_temporal_alignment: "آج کی تاریخ",
    home_weekly_engagement: "ہفتہ وار مطالعہ کی سرگرمی",
    home_status_optimized: "حیثیت: بہترین",
    home_gpa_estimate: "جی پی اے تخمینہ",
    home_academic_standing: "تعلیمی حیثیت",
    home_superior_performance: "بہترین کارکردگی کا پتہ چلا۔",
    home_presence_analytics: "حاضری کا تجزیہ",
    home_maintain_trajectory: "اپنی رفتار برقرار رکھیں۔",
    home_bulletin_history: "بلیٹن ہسٹری",
    home_last_synced: "آخری مطابقت",
    home_portal_version: "پورٹل ورژن 4.0.2 مستحکم",
    header_no_match: "کوئی صفحہ نہیں ملا",
    header_search_placeholder: "صفحات تلاش کریں...",
  },
  ur_roman: {
    portal_title: "ILMA Student Portal",
    command_center: "Command Center",
    welcome_msg:
      "Academic management ki agli nasal mein khush amdeed. Apne courses ki nigraani karein.",
    dashboard: "Dashboard",
    grades: "Parhai Ka Link",
    financial: "Fees Ka Hisab",
    assignments: "Assignment Hub",
    campus: "Campus Ki Khabrein",
    appearance: "Design Badalain",
    portal: "Portal Node",
    profile: "Student Profile",
    schedule: "Class Ka Time",
    notifications: "Alerts & Messages",
    logout: "Bahir Nikalain",
    search: "Kuch dhondein...",
    academic_trajectory: "Parhai Ka Graph",
    system_alerts: "Zaroori Khabrein",
    attendance: "Hazri Ka Pulse",
    gpa: "GPA Ka Hisab",
    fee_breakdown: "Fees Ki Detail",
    scholarship: "Scholarship Node",
    extracurricular: "Baher Ki Activities",
    assignment_header: "Assignment Sanctuary",
    assignment_subtitle:
      "Apne parhai ke targets check karein aur feedback dekhain.",
    active_deadlines: "Active Deadlines",
    performance_equilibrium: "Performance Check",
    mission_history: "Purani History",
    initialize_uplink: "Upload Karein",
    language_label: "Roman",
    // Grades Page
    grades_title: "Parhai Ka Link",
    grades_subtitle:
      "Aapki academic history aur degree syncing ki digital tasveer.",
    active_semester: "Active Semester Node",
    semester_batch: "Spring 2026 Batch",
    module_entry: "Course Name",
    index: "GPA",
    rank: "Grade",
    sync_status: "Result Status",
    degree_completion: "Degree Poori Hone Ka Hub",
    earned_credits: "Poore Kiye Gaye Credits",
    academic_status: "Pahrhai Ki Status",
    cumulative_index: "Total GPA",
    secure_transcript: "Transcript Download Karein",
    // Schedule Page
    schedule_title: "Class Ka Time Table",
    schedule_subtitle: "Apna hafta-war schedule check karein.",
    weekly_schedule: "Hafta-war Schedule",
    spring_semester: "Spring Semester 2026",
    time_slot: "Time Slot",
    export_pdf: "PDF Download",
    // Notifications Page
    bulletin_center: "Alerts Center",
    bulletin_subtitle: "Apne campus notifications aur news check karein.",
    dismiss_all: "Sab Hatayein",
    unread_alerts: "Naye Alerts",
    common_status: "Status",
    common_progress: "Progress",
    common_join: "Join Karein",
    common_view: "Dekhain",
    common_cancel: "Cancel",
    day_mon: "Peer",
    day_tue: "Mangal",
    day_wed: "Budh",
    day_thu: "Jumeraat",
    day_fri: "Jumma",
    day_sat: "Hafta",
    day_sun: "Itwaar",
    auth_login_heading: "Wapsi Mubarak",
    auth_login_subtitle: "Jari rakhne ke liye apne student account mein login karein.",
    auth_email_label: "Email Address",
    auth_password_label: "Password",
    auth_forgot_password: "Password Bhool Gaye?",
    auth_signing_in: "Login ho raha hai…",
    auth_sign_in: "Login Karein",
    auth_no_account: "Account nahi hai?",
    auth_create_account: "Account Banayein",
    auth_uni_name: "ILMA University",
    auth_student_portal: "Student Portal",
    auth_panel_login_desc:
      "Apne courses, grades, schedule aur campus notifications ek hi jagah check karein.",
    auth_stat_students: "15,000+ Active Students",
    auth_stat_faculty: "200+ Expert Faculty",
    auth_stat_ranked: "Number 1 Private University",
    auth_join_ilma: "ILMA Join Karein",
    auth_signup_panel_title2: "Hackathon 2026",
    auth_panel_signup_desc:
      "Apna student account banayein aur university ke tamam resources, events aur bohat kuch turant access karein.",
    auth_feature_instant: "Sign Up Par Turant Access",
    auth_feature_secure: "Mehfooz Aur Encrypted Data",
    auth_feature_247: "24 / 7 Portal Dastyaab",
    auth_feature_leaderboard: "Hackathon Leaderboard",
    auth_signup_subtitle: "Neeche apni student details ke sath register karein.",
    auth_fullname_label: "Pura Naam",
    auth_studentid_label: "Student ID",
    auth_creating_account: "Account ban raha hai…",
    auth_have_account: "Pehle se account hai?",
    auth_sign_in_link: "Login Karein",
    auth_forgot_heading: "Password Bhool Gaye?",
    auth_forgot_subtitle:
      "Apna registered email likhein, hum aapko password reset link bhejein ge.",
    auth_sending: "Bheja ja raha hai…",
    auth_send_reset_link: "Reset Link Bhejein",
    auth_back_to_login: "Login Par Wapas Jayein",
    auth_reset_heading: "Naya Password Set Karein",
    auth_reset_subtitle_prefix: "Iske liye mazboot password banayein",
    auth_new_password_label: "Naya Password",
    auth_confirm_password_label: "Password Confirm Karein",
    auth_updating: "Update ho raha hai…",
    auth_reset_password_btn: "Password Reset Karein",
    auth_passwords_match: "✓ Passwords match karte hain",
    auth_passwords_no_match: "✗ Passwords match nahi karte",
    auth_pw_weak: "Kamzor",
    auth_pw_fair: "Theek Thaak",
    auth_pw_good: "Acha",
    auth_pw_strong: "Mazboot",
    auth_pw_suffix: "password",
    auth_email_placeholder: "yourname@ilmauniversity.edu",
    auth_password_placeholder: "Apna password likhein",
    auth_password_placeholder_create: "Ek mazboot password banayein",
    auth_fullname_placeholder: "John Doe",
    auth_studentid_placeholder: "2023-CS-001",
    auth_new_password_placeholder: "Kam az kam 6 characters",
    auth_confirm_password_placeholder: "Apna naya password dobara likhein",
    profile_title: "Student Identity",
    profile_subtitle: "Apni academic profile aur digital credentials manage karein.",
    profile_official_id: "Official ID / 2026",
    profile_valid_thru: "Valid Thru",
    profile_scan_verify: "Verify Karne Ke Liye Scan Karein",
    profile_qr_note: "Yeh ILMA University ki milkiyat hai. Milne par administration ko wapas karein.",
    profile_active: "Active",
    profile_stat_gpa: "Total GPA",
    profile_stat_attendance: "Attendance",
    profile_stat_credits: "Total Credits",
    profile_stat_points: "Portal Points",
    profile_account_heading: "Account Profile",
    profile_account_subtitle: "Portal par apni public identity update karein.",
    profile_edit: "Profile Edit Karein",
    profile_save: "Changes Save Karein",
    profile_fullname_label: "Pura Naam",
    profile_studentid_label: "Official Student ID",
    profile_email_label: "Verified Email Address",
    profile_bio_label: "Personal Academic Bio",
    profile_security_status: "Security Status",
    profile_reset_credentials: "Credentials Reset Karein",
    profile_termination: "Session Termination",
    profile_deactivate: "Session Deactivate Karein",
    notfound_error: "Error 404",
    notfound_title: "Page Nahi Mila",
    notfound_desc: "Jo page aap dhoond rahe hain wo mojood nahi ya move ho chuka hai.",
    notfound_home: "Home Par Wapas Jayein",
    notfound_portal: "Portal Kholein",
    error_title: "Kuch Ghalat Ho Gaya",
    error_desc: "Page load nahi ho saka. Dobara try karein ya kisi aur page par jayein.",
    financial_subtitle:
      "Apna fiscal node manage karein, transactions track karein aur scholarship allocations dekhein.",
    financial_balance_hub: "Current Balance",
    financial_scholarship_metrics: "Scholarship Metrics",
    financial_eligibility_sync: "Eligibility Sync",
    financial_ledger_matrix: "Ledger Matrix",
    financial_filter_hub: "Filter Hub",
    financial_apply_installments: "Installments Ke Liye Apply Karein",
    financial_th_txid: "Transaction ID",
    financial_th_desc: "Description",
    financial_th_amount: "Amount",
    financial_th_method: "Method",
    generate_voucher: "Voucher Banayein",
    campus_subtitle:
      "ILMA ki digital dharkan. Latest news, events aur campus guilds se juday rahein.",
    campus_live_stream: "Live Stream",
    campus_online: "Online",
    campus_historical_logs: "Purani Activities",
    campus_event_nexus: "Event Nodes",
    campus_guild_directory: "Verified Campus Guilds",
    campus_secure_token: "Seat Confirm Karein",
    campus_join_node: "Join Karein",
    campus_members_suffix: "Members",
    campus_digital_hub: "Digital Campus Hub",
    portal_active_enrollment: "Active Enrollment",
    portal_courses_suffix: "Courses",
    portal_no_courses: "Abhi tak koi course enroll nahi kiya",
    portal_marketplace: "Marketplace",
    portal_timeline: "Timeline",
    appearance_subtitle:
      "Apne portal ka look badalain aur Command Center ko apni marzi ka banayein.",
    appearance_theme_archetypes: "Theme Ki Qisme",
    appearance_mode_sync: "Mode Synchronizer",
    appearance_solar: "Din Ka Mode",
    appearance_night: "Raat Ka Mode",
    appearance_font_matrix: "Font Matrix",
    appearance_typography_scaling: "Font Size",
    appearance_compact: "Chota",
    appearance_standard: "Standard",
    appearance_expanded: "Bara",
    appearance_reset_protocols: "Sab Kuch Reset Karein",
    appearance_factory_reboot: "Factory Reset Shuru Karein",
    assignments_request_extension: "Extension Ki Request Karein",
    assignments_th_deployed: "Jama Kiya Gaya Kaam",
    assignments_th_index: "Index Score",
    assignments_th_remarks: "Faculty Ki Raye",
    assignments_score: "Score",
    schedule_lunch_break: "Khane Ka Waqt",
    schedule_main_block: "Main Block",
    schedule_info_rooms: "Rooms 201-205, Labs",
    schedule_info_faculty_hours_title: "Faculty Ke Auqat",
    schedule_info_faculty_hours_text: "Peer se Jumeraat: Subha 10 se Dopeher 12",
    schedule_info_note_title: "Note",
    schedule_info_note_text: "Lab sessions mein hazri zaroori hai.",
    home_portal_btn: "Portal",
    home_sync_timetable: "Timetable Dekhein",
    home_student_node: "Student Node",
    home_uplink_active: "Uplink: Active",
    home_latency_prefix: "Latency",
    home_live_time: "Live System Time",
    home_active_sync: "Active Sync",
    home_temporal_alignment: "Aaj Ki Tareekh",
    home_weekly_engagement: "Hafta-war parhai ki activity",
    home_status_optimized: "Status: Behtareen",
    home_gpa_estimate: "GPA Andaza",
    home_academic_standing: "Academic Standing",
    home_superior_performance: "Behtareen performance mili.",
    home_presence_analytics: "Hazri Ka Tajzia",
    home_maintain_trajectory: "Apni raftar barqarar rakhein.",
    home_bulletin_history: "Bulletin History",
    home_last_synced: "Aakhri Sync",
    home_portal_version: "Portal Version 4.0.2 Stable",
    header_no_match: "Koi page nahi mila",
    header_search_placeholder: "Pages talaash karein...",
  },
};

export const applyLanguage = (lang) => {
  localStorage.setItem("portal-lang", lang);
  document.documentElement.lang = lang === "ur" ? "ur" : "en";
  document.documentElement.dir = lang === "ur" ? "rtl" : "ltr";
};

export const getTranslation = (key) => {
  const lang = localStorage.getItem("portal-lang") || "en";
  // A stale or hand-edited portal-lang leaves translations[lang] undefined.
  // This runs during render across every page, so indexing it directly turned
  // an unknown language into a blank app.
  const dict = translations[lang] || translations.en;
  return dict[key] || translations.en[key] || key;
};
